services:
  db:
    image: pgvector/pgvector:pg18
    container_name: nexus_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: nexus_db
    volumes:
      - postgress_data:/var/lib/postgresql

  redis:
    image: redis:alpine
    container_name: nexus_cache
    ports:
      - "6379:6379"
volumes:
  postgress_data:
